### ISSUE TITLE
Kontext-Diagramm-Feedback

### ISSUE THREAD

**Issue by bjoernmichels** [Domiuetz/SWA-Hausaufgaben#2]
![image](https://user-images.githubusercontent.com/47139880/149537104-3a8019e3-b08a-4500-b2f7-19da8304b040.png)

1. Was ist ein lineares Spielt. Dies könnte im Text erläutert werden (oder in einem Glossar). Der Title der Anwendung ist vermutlich "HockeyMatch"  und Lienares Spiel ist wohl schon einen Erläuterung.
2. Im Kontext-Diagramm beschriften wir die Beziehungen mit "ausgetauschten Informationen" In diesem Fall scheinen es zwei Informationen ausgetauscht zu werden: <br> << Antworten (Ja,Nein) <br> Fragen >>

**Comment by bjoernmichels** [comment]
Das Kontext-Diagramm sieht jetzt gut aus :smile:  .
Einzig der Pfeil für die "Fragen" sollte in die andere Richtung zeigen? Denn das HockeyMatch stellt dem Player fragen.
![image](https://user-images.githubusercontent.com/47139880/153053964-bf1e3f8d-9ceb-436c-b44d-e8ce4b7f8b34.png)

**Comment by Domiuetz** [comment]
Danke für den Hinweis 😄
