### ISSUE TITLE
Bemerkungen zum UseCase

### ISSUE THREAD

**Issue by bjoernmichels** [Domiuetz/SWA-Hausaufgaben#5]
Das UseCase Diagramm sieht jetzt gut aus :smile:

Optimierungen könnten sein:
1) `include` und `extend` habe immer Pfeile, also eine Richtung: <br>include: A beinhaltet B; <br>extenct: A erweitert B;
2) Das `Spiel starten`, `Spiel beenden` und `Fragen beantworten` wären Teil von `Spiel spielen` und könnten also weggelassen werden. Das Starten und Beenden kann in der UseCase-Beschreibung dokumentiert werden.

**UseCase Beschreibung `Spiel spielen`**
Step1. Der `Player` startet das Spiel
Step2. `HockeyMatch` stellt dem `Player` Fragen
Step3. Der `Player` beantwortet die Frage.
Step4a. `HockeyMatch` stellt die nächste Frage --> Step 3.
Step4b. `HockeyMatch` hat keine Fragen mehr und fragt den `Player` ob dieser nochmals spielen möchte
Step5a. Der `Player` antwortet Ja --> Step 2.
Step5b. Der `Player` antwortet Nein -> Das Spiel endet.

![image](https://user-images.githubusercontent.com/47139880/156443851-2a681b0b-f12a-4b1e-a9d2-a8b1b5ef1124.png)

**Comment by Domiuetz** [comment]
Danke für deine Hinweise. Wäre es denn so nun gut?

**Comment by bjoernmichels** [comment]
Ja, das sieht gut aus :smile: 

Der Pfeil sollte wohl in die andere Richtung gehen denn `Fragen beantworten` "erweitert" das `Spiel spielen`. Gelesen wird in die Pfeilrichtung (nicht links nach rechts).
![image](https://user-images.githubusercontent.com/47139880/157073977-56e58955-b5ab-4722-93c2-a2de8f141155.png)


Bezüglich der Beschreibung des UseCases Spiel spielen, muss ich noch anmerken, dass ich den Code nicht studiert habe soass ich nicht weiss ob der Ablauf inhaltlich stimmt.... was aber für diese Übung auch nicht relevant ist :wink:
