### ISSUE TITLE
Bemerkungen zur Verteilungssicht

### ISSUE THREAD

**Issue by bjoernmichels** [Domiuetz/SWA-Hausaufgaben#6]
![image](https://user-images.githubusercontent.com/47139880/156658042-38267d74-f2d4-43a3-8964-be7852bbb955.png)

Die Verteilungssicht sieht soweit ~ok aus.

1. Die Hardware `PC` sollte als eigener Node dargestellt werden. Die Ausführungsumgebung auch als eigener Node zB `Windows 10 und neuer`.
![image](https://user-images.githubusercontent.com/47139880/156657712-2644f967-0111-4cc5-85c8-e4fb3e9ec854.png)
2. Das Spiel heisst im Kontext- und UseCase-Diagramm jeweils `HockeyMatch`. Da es sich um die selbe Software in der Verteilungssicht handelt, sollte diese wohl auch den selben Namen haben.

**Comment by Domiuetz** [comment]
1. Sollte ich denn für "Windows" nicht auch ein Software-Embleme benutzen?

**Comment by Domiuetz** [comment]
so etwa in der Art?

![Verteilungssicht_Diagramm_V2](https://user-images.githubusercontent.com/97550314/157064405-1526519d-3347-485c-89e3-f776b5118e5e.png)

**Comment by bjoernmichels** [comment]
Das Software resp. Komponenten-Symbol würde ich bei `Windows 10 und neuer` nicht verwenden. Ich hab das noch nie so gesehen... aber auch nicht wirklich eine Begründen warum nicht... Ausser vielleicht die Spitzfindigkeit das `executionEnvironment` der Stereotyp ist und nicht Komponente.

Es ist übrigens `executionEnvironment` (Ausführungsumgebung) statt `executiveEnvironement` (GeschäftsführerUmgebung) :laughing:
